icon_resources = {
    # File icons
    "python_icon": "python",
    "default_icon": "file",
    "lua_icon": "lua",
    "html_icon": "html",
    "css_icon": "css",
    "javascript_icon": "javascript",
    "json_icon": "json",
    "image_icon": "image",
    "git_icon": "git",
    "markdown_icon": "markdown",
    "python_misc": "python-misc",
    "config_icon": "settings",
    "batch": "exe",
    "readme": "readme",
    "security": "lock",
    "dependabot": "dependabot",
    "conduct": "conduct",
    "license": "certificate",
    "contributing": "contributing",
    "yaml": "yaml",
    # Folder icons
    "scripts_folder": "folder-scripts",
    "python_folder": "folder-python",
    "github_folder": "folder-github",
    "environment_folder": "folder-environment",
    "git_folder": "folder-git",
    "zenith": "zenith",
    "github_workflow": "folder-gh-workflows",
    "misc": "folder-other",
    "assets": "folder-resource",
    "svg_folder": "folder-svg",
    "images_folder": "folder-images",
    "components_folder": "folder-components",
    "core_folder": "folder-core",
    "framework_folder": "folder-tools",
    "lexer_folder": "folder-syntax",
}
