return {
  -- Catppuccin Macchiato colors
  rosewater = "#f4dbd6",
  flamingo = "#f0c6c6",
  pink = "#f5bde6",
  mauve = "#c6a0f6",
  red = "#ed8796",
  maroon = "#ee99a0",
  peach = "#f5a97f",
  yellow = "#eed49f",
  green = "#a6da95",
  teal = "#8bd5ca",
  sky = "#91d7e3",
  sapphire = "#7dc4e4",
  blue = "#8aadf4",
  lavender = "#b7bdf8",
  text = "#cad3f5",
  subtext1 = "#b8c0e0",
  subtext0 = "#a5adcb",
  overlay2 = "#939ab7",
  overlay1 = "#8087a2",
  overlay0 = "#6e738d",
  surface2 = "#5b6078",
  surface1 = "#494d64",
  surface0 = "#363a4f",
  base = "#24273a",
  mantle = "#1e2030",
  crust = "#181926",

  -- Application color scheme
  background = "#24273a",
  foreground = "#cad3f5",
  cursor = "#f4dbd6",
  selection_bg = "#5b6078",
  selection_fg = "#cad3f5",

  -- Lexer color scheme (mixed macchiato)
  default = "#D9E0EE",
  keyword = "#7dc4e4",
  operator = "#F8BD96",
  brace = "#F5C2E7",
  defclass = "#F8BD96",
  string = "#ABE9B3",
  string2 = "#F5E0DC",
  comment = "#89B4FA",
  numbers = "#F5C2E7",
  class = "#c6a0f6",
  func = "#F28FAD",
  operators = "#8aadf4",
  matched_brace_bg = "#F5C2E7",
  matched_brace_fg = "	#a5adcb",
  unmatched_brace_bg = "#ed8796",
  unmatched_brace_fg = "	#a5adcb",
  regex = "#F8BD96",

  -- Calltip color scheme
  calltip_bg = "#24273a",
  calltip_fg = "#cad3f5",
  calltip_highlight = "#f5bde6",
  calltip_function = "#8aadf4",
  calltip_param = "#a6da95",
  calltip_current_param = "#f0c6c6",
  calltip_optional_param = "#c6a0f6",
  calltip_description = "#b8c0e0",

  -- Codespace color scheme
  caret = "#b8c0e0",
  margin_fg = "#a5adcb",
  margin_bg = "#1a1b26",
  folding_bg = "#1a1b26",
  folding_fg = "#181926",
  breakpoint = "#ed8796",
  unsaved = "#a6da95",
  intend = "#939ab7",
  marker = "#8087a2",
  marker_text = "#363a4f",
  background_codespace = "#16161e",

  -- Tabline color scheme
  tab_bg = "#16161e",
  tabselect = "#8087a2",
  tab_bg_hover = "#1f2335",

  -- Statusline color scheme
  statusbar_bg = "#24273a",
  statusbar_fg = "#cad3f5",
  statusbar_separator = "#494d64",
  editmode_readonly = "#a6da95",
  editmode_edit = "#ee99a0",

  -- Filetree color scheme
  filetree_bg = "#1e2030",
  filetree_fg = "#cad3f5",
  filetree_selected = "#494d64",
  filetree_hover = "#363a4f",

  -- Right Sidebar
  sidebar_bg = "#1e2030",
  sidebar_fg = "#cad3f5",
  sidebar_button = "#494d64",
  sidebar_button_hover = "#5b6078",

  -- Menubar color scheme
  menubar_bg = "#24273a",
  menubar_fg = "#cad3f5",
  menubar_selected = "#494d64",
  menu_bg = "#1e2030",
  menu_fg = "#cad3f5",
  menu_selected = "#494d64",
  menu_separator = "#5b6078",

  -- Title Bar
  titlebar_bg = "#24273a",
  titlebar_fg = "#cad3f5",
  titlebar_button = "#494d64",
  titlebar_button_hover = "#5b6078",

  -- C specific colors
  c_comment_doc = "#89B4FA",
  c_uuid = "#F5C2E7",
  c_preprocessor = "#F8BD96",
  c_identifier = "#ABE9B3",
  c_unclosed_string = "#ed8796",
  c_verbatim_string = "#7dc4e4",
  c_comment_line_doc = "#c6a0f6",
  c_keyword_set2 = "#F28FAD",
  c_comment_doc_keyword = "#8aadf4",
  c_comment_doc_keyword_error = "#ed8796",
  c_global_class = "#FAE3B0",
  c_raw_string = "#A6E3A1",
  c_triple_quoted_verbatim_string = "#94E2D5",
  c_hash_quoted_string = "#F2CDCD",
  c_preprocessor_comment = "#B5E8E0",
  c_preprocessor_comment_line_doc = "#DDB6F2",

  -- HTML specific colors
  html_tag = "#F28FAD",
  html_unknown_tag = "#ed8796",
  html_attribute = "#ABE9B3",
  html_unknown_attribute = "#F5C2E7",
  html_other_in_tag = "#8aadf4",
  html_entity = "#c6a0f6",
  html_tag_end = "#F28FAD",
  html_xml_start = "#7dc4e4",
  html_xml_end = "#7dc4e4",
  html_script = "#F8BD96",
  html_asp_at_start = "#ed8796",
  html_asp_start = "#ed8796",
  html_cdata = "#89B4FA",
  html_php_start = "#F5C2E7",
  html_value = "#ABE9B3",

  -- CSS specific colors
  css_tag = "#F28FAD",
  css_class = "#ABE9B3",
  css_pseudo_class = "#c6a0f6",
  css_unknown_pseudo_class = "#ed8796",
  css_property = "#7dc4e4",
  css_unknown_property = "#ed8796",
  css_value = "#F5C2E7",
  css_id_selector = "#F8BD96",
  css_important = "#ed8796",
  css_at_rule = "#8aadf4",
  css_attribute = "#ABE9B3",
  css_pseudo_element = "#c6a0f6",
  css_extended_property = "#7dc4e4",
  css_extended_pseudo_class = "#c6a0f6",
  css_extended_pseudo_element = "#c6a0f6",

  -- JSON specific colors
  json_unclosed_string = "#ed8796",
  json_property = "#7dc4e4",
  json_escape_sequence = "#F5C2E7",
  json_iri = "#8aadf4",
  json_iri_compact = "#8aadf4",
  json_keyword_ld = "#c6a0f6",
  json_error = "#ed8796",

  -- Lua specific colors
  lua_literal_string = "#ABE9B3",
  lua_preprocessor = "#F8BD96",
  lua_unclosed_string = "#ed8796",
  lua_basic_functions = "#8aadf4",
  lua_string_table_maths_functions = "#7dc4e4",
  lua_coroutines_io_system_facilities = "#c6a0f6",
  lua_keyword_set5 = "#F28FAD",
  lua_keyword_set6 = "#F28FAD",
  lua_keyword_set7 = "#F28FAD",
  lua_keyword_set8 = "#F28FAD",
  lua_label = "#F5C2E7",

  -- Markdown specific colors
  md_default = "#cad3f5",
  md_header = "#8aadf4",
  md_code = "#a6da95",
  md_link = "#7dc4e4",
  md_url = "#f5bde6",
  md_blockquote = "#91d7e3",
  md_emphasis = "#f5a97f",
  md_strong = "#ed8796",
  md_list_item = "#eed49f",
  md_horizontal_rule = "#8087a2",
  md_code_block = "#a6da95",
  md_code_block_bg = "#363a4f",
  md_comment = "#8087a2",

  -- XML specific colors
  xml_tag = "#F28FAD",
  xml_unknown_tag = "#ed8796",
  xml_attribute = "#ABE9B3",
  xml_unknown_attribute = "#F5C2E7",
  xml_other_in_tag = "#8aadf4",
  xml_entity = "#c6a0f6",
  xml_tag_end = "#F28FAD",
  xml_start = "#7dc4e4",
  xml_end = "#7dc4e4",
  xml_script = "#F8BD96",
  xml_cdata = "#89B4FA",
  xml_question = "#F5C2E7",
  xml_value = "#ABE9B3",

  -- YAML specific colors
  yaml_identifier = "#ABE9B3",
  yaml_reference = "#8aadf4",
  yaml_document_delimiter = "#F28FAD",
  yaml_text_block_marker = "#F5C2E7",
  yaml_syntax_error_marker = "#ed8796",

  -- Java specific colors
  java_identifier = "#ABE9B3",
  java_javadoc = "#89B4FA",
  java_javadoc_keyword = "#F5C2E7",

  -- Perl specific colors
  perl_error = "#ed8796",
  perl_pod = "#89B4FA",
  perl_identifier = "#ABE9B3",
  perl_scalar = "#F5C2E7",
  perl_array = "#F8BD96",
  perl_hash = "#7dc4e4",
  perl_symbol_table = "#c6a0f6",
  perl_substitution = "#F28FAD",
  perl_backtick_here_document = "#8aadf4",
  perl_quoted_string_q = "#A6E3A1",
  perl_quoted_string_qq = "#F5E0DC",
  perl_quoted_string_qx = "#FAE3B0",
  perl_quoted_string_qr = "#DDB6F2",
  perl_quoted_string_qw = "#B5E8E0",
  perl_pod_verbatim = "#94E2D5",
  perl_subroutine_prototype = "#F2CDCD",
  perl_format_identifier = "#EBA0AC",
  perl_format_body = "#F5C2E7",

  -- Bash specific colors
  bash_error = "#ed8796",
  bash_identifier = "#ABE9B3",
  bash_scalar = "#F5C2E7",
  bash_parameter_expansion = "#F8BD96",
  bash_backticks = "#7dc4e4",
  bash_here_document_delimiter = "#c6a0f6",
  bash_single_quoted_here_document = "#8aadf4",

  -- Batch specific colors
  batch_label = "#F5C2E7",
  batch_hide_command_char = "#7dc4e4",
  batch_external_command = "#F8BD96",
  batch_variable = "#ABE9B3",

  -- CMake specific colors
  cmake_string_left_quote = "#F5C2E7",
  cmake_string_right_quote = "#F5C2E7",
  cmake_variable = "#ABE9B3",
  cmake_label = "#F8BD96",
  cmake_keyword_set3 = "#7dc4e4",
  cmake_block_while = "#c6a0f6",
  cmake_block_foreach = "#F28FAD",
  cmake_block_if = "#8aadf4",
  cmake_block_macro = "#F5E0DC",
  cmake_string_variable = "#FAE3B0",

  -- SQL specific colors
  sql_comment_doc = "#89B4FA",
  sql_plus_keyword = "#F5C2E7",
  sql_plus_prompt = "#F8BD96",
  sql_identifier = "#ABE9B3",
  sql_plus = "#7dc4e4",
  sql_plus_command = "#c6a0f6",
  sql_quoted_identifier = "#F28FAD",
  sql_q_operator = "#8aadf4",

  -- Ruby specific colors
  ruby_error = "#ed8796",
  ruby_pod = "#89B4FA",
  ruby_identifier = "#ABE9B3",
  ruby_global = "#F5C2E7",
  ruby_symbol = "#F8BD96",
  ruby_module_name = "#7dc4e4",
  ruby_instance_variable = "#c6a0f6",
  ruby_class_variable = "#F28FAD",
  ruby_backtick_here_document = "#8aadf4",
  ruby_here_document = "#F5E0DC",
  ruby_percent_string_q = "#FAE3B0",
  ruby_percent_string_Q = "#DDB6F2",

  -- Properties specific colors
  prop_default = "#cad3f5",
  prop_key = "#7dc4e4",
  prop_section = "#eed49f",
  prop_assignment = "#91d7e3",
  prop_value = "#a6da95",
  prop_comment = "#8087a2",
}
