return {
  -- Catppuccino color scheme (mixed macchiato)
  default = "#D9E0EE",
  keyword = "#7dc4e4",
  operator = "#F8BD96",
  brace = "#F5C2E7",
  defclass = "#F8BD96",
  string = "#ABE9B3",
  string2 = "#F5E0DC",
  comment = "#89B4FA",
  numbers = "#F5C2E7",
  class = "#c6a0f6",
  func = "#F28FAD",
  operators = "#8aadf4",
  matched_brace_bg = "#F5C2E7",
  matched_brace_fg = "	#a5adcb",
  unmatched_brace_bg = "#ed8796",
  unmatched_brace_fg = "	#a5adcb",
  regex = "#F8BD96",

  -- Codespace color scheme
  caret = "#b8c0e0",
  margin_fg = "#a5adcb",
  margin_bg = "#444",
  folding_bg = "#444",
  folding_fg = "#333",
  breakpoint = "#ed8796",
  unsaved = "#a6da95",
  intend = "#939ab7",
  marker = "#8087a2",
  marker_text = "#363a4f",

  -- Tabline color scheme
  tab_bg = "#333",
  tabselect = "#8087a2",
  tab_bg_hover = "#444",

  -- Statusline color scheme

  -- Filetree color scheme

  -- Menubar color scheme

  -- HTML specific colors
  html_tag = "#F28FAD",
  html_unknown_tag = "#ed8796",
  html_attribute = "#ABE9B3",
  html_unknown_attribute = "#F5C2E7",
  html_other_in_tag = "#8aadf4",
  html_entity = "#c6a0f6",
  html_tag_end = "#F28FAD",
  html_xml_start = "#7dc4e4",
  html_xml_end = "#7dc4e4",
  html_script = "#F8BD96",
  html_asp_at_start = "#ed8796",
  html_asp_start = "#ed8796",
  html_cdata = "#89B4FA",
  html_php_start = "#F5C2E7",
  html_value = "#ABE9B3",

  -- CSS specific colors
  css_tag = "#F28FAD",
  css_class = "#ABE9B3",
  css_pseudo_class = "#c6a0f6",
  css_unknown_pseudo_class = "#ed8796",
  css_property = "#7dc4e4",
  css_unknown_property = "#ed8796",
  css_value = "#F5C2E7",
  css_id_selector = "#F8BD96",
  css_important = "#ed8796",
  css_at_rule = "#8aadf4",
  css_attribute = "#ABE9B3",
  css_pseudo_element = "#c6a0f6",
  css_extended_property = "#7dc4e4",
  css_extended_pseudo_class = "#c6a0f6",
  css_extended_pseudo_element = "#c6a0f6",

  -- JSON specific colors
  json_unclosed_string = "#ed8796",
  json_property = "#7dc4e4",
  json_escape_sequence = "#F5C2E7",
  json_iri = "#8aadf4",
  json_iri_compact = "#8aadf4",
  json_keyword_ld = "#c6a0f6",
  json_error = "#ed8796",

  -- Lua specific colors
  lua_literal_string = "#ABE9B3",
  lua_preprocessor = "#F8BD96",
  lua_unclosed_string = "#ed8796",
  lua_basic_functions = "#8aadf4",
  lua_string_table_maths_functions = "#7dc4e4",
  lua_coroutines_io_system_facilities = "#c6a0f6",
  lua_keyword_set5 = "#F28FAD",
  lua_keyword_set6 = "#F28FAD",
  lua_keyword_set7 = "#F28FAD",
  lua_keyword_set8 = "#F28FAD",
  lua_label = "#F5C2E7",

  -- Markdown specific colors
  md_special = "#F8BD96",
  md_strong_emphasis = "#F28FAD",
  md_emphasis = "#c6a0f6",
  md_header1 = "#7dc4e4",
  md_header2 = "#7dc4e4",
  md_header3 = "#7dc4e4",
  md_header4 = "#7dc4e4",
  md_header5 = "#7dc4e4",
  md_header6 = "#7dc4e4",
  md_prechar = "#F5C2E7",
  md_unordered_list_item = "#ABE9B3",
  md_ordered_list_item = "#ABE9B3",
  md_block_quote = "#8aadf4",
  md_strikeout = "#ed8796",
  md_horizontal_rule = "#F5C2E7",
  md_link = "#8aadf4",
  md_code_backticks = "#F8BD96",
  md_code_block = "#F8BD96",
  md_code_fence = "#F8BD96",
}
