return {
  new_tab = "Ctrl+N",
  codespace = "Ctrl+Shift+N",
  open = "Ctrl+O",
  open_folder = "Ctrl+Shift+O",
  save = "Ctrl+S",
  save_as = "Ctrl+Shift+S",
  close_tab = "Ctrl+W",
  close_all_tabs = "Ctrl+Shift+W",
  toggle_file_tree = "Ctrl+F",
  next_tab = "Ctrl+Tab",
  prev_tab = "Ctrl+Shift+Tab",
  exit = "Ctrl+Shift+Q",
  edit_mode = "Ctrl+E",
}
