return {
  -- Tokyo Night Storm colors
  bg = "#24283b",
  bg_dark = "#1f2335",
  bg_highlight = "#292e42",
  terminal_black = "#414868",
  fg = "#c0caf5",
  fg_dark = "#a9b1d6",
  fg_gutter = "#3b4261",
  dark3 = "#545c7e",
  comment = "#565f89",
  dark5 = "#737aa2",
  blue0 = "#3d59a1",
  blue = "#7aa2f7",
  cyan = "#7dcfff",
  blue1 = "#2ac3de",
  blue2 = "#0db9d7",
  blue5 = "#89ddff",
  blue6 = "#b4f9f8",
  blue7 = "#394b70",
  magenta = "#bb9af7",
  magenta2 = "#ff007c",
  purple = "#9d7cd8",
  orange = "#ff9e64",
  yellow = "#e0af68",
  green = "#9ece6a",
  green1 = "#73daca",
  green2 = "#41a6b5",
  teal = "#1abc9c",
  red = "#f7768e",
  red1 = "#db4b4b",

  surface0 = "#1d202f",
  surface1 = "#282d42",

  -- Application color scheme
  background = "#1f2335",
  foreground = "#c0caf5",
  cursor = "#c0caf5",
  selection_bg = "#364A82",
  selection_fg = "#c0caf5",

  -- Lexer color scheme
  default = "#c0caf5",
  keyword = "#9d7cd8",
  operator = "#89ddff",
  brace = "#9d7cd8",
  defclass = "#e0af68",
  string = "#9ece6a",
  string2 = "#b4f9f8",
  comment = "#565f89",
  numbers = "#ff9e64",
  class = "#e0af68",
  func = "#7aa2f7",
  operators = "#89ddff",
  matched_brace_bg = "#565f89",
  matched_brace_fg = "#c0caf5",
  unmatched_brace_bg = "#f7768e",
  unmatched_brace_fg = "#c0caf5",
  regex = "#b4f9f8",

  -- Calltip color scheme
  calltip_bg = "#1f2335",
  calltip_fg = "#c0caf5",
  calltip_highlight = "#9d7cd8",
  calltip_function = "#7aa2f7",
  calltip_param = "#9ece6a",
  calltip_current_param = "#e0af68",
  calltip_optional_param = "#bb9af7",
  calltip_description = "#a9b1d6",

  -- Codespace color scheme
  caret = "#c0caf5",
  margin_fg = "#3b4261",
  margin_bg = "#1f2335",
  folding_bg = "#1f2335",
  folding_fg = "#3b4261",
  breakpoint = "#f7768e",
  unsaved = "#9ece6a",
  intend = "#3b4261",
  marker = "#414868",
  marker_text = "#c0caf5",
  background_codespace = "#24283b",

  -- Tabline color scheme
  tab_bg = "#1f2335",
  tabselect = "#7aa2f7",
  tab_bg_hover = "#292e42",

  -- Statusline color scheme
  statusbar_bg = "#1f2335",
  statusbar_fg = "#a9b1d6",
  statusbar_separator = "#3b4261",
  editmode_readonly = "#9ece6a",
  editmode_edit = "#7aa2f7",

  -- Filetree color scheme
  filetree_bg = "#1f2335",
  filetree_fg = "#a9b1d6",
  filetree_selected = "#364A82",
  filetree_hover = "#292e42",

  -- Right Sidebar
  sidebar_bg = "#1f2335",
  sidebar_fg = "#a9b1d6",
  sidebar_button = "#414868",
  sidebar_button_hover = "#545c7e",

  -- Menubar color scheme
  menubar_bg = "#1f2335",
  menubar_fg = "#c0caf5",
  menubar_selected = "#364A82",
  menu_bg = "#24283b",
  menu_fg = "#c0caf5",
  menu_selected = "#364A82",
  menu_separator = "#3b4261",

  -- Title Bar
  titlebar_bg = "#1f2335",
  titlebar_fg = "#c0caf5",
  titlebar_button = "#414868",
  titlebar_button_hover = "#545c7e",

  -- Language-specific colors
  -- (Using Tokyo Night Storm equivalents)

  -- C specific colors
  c_comment_doc = "#565f89",
  c_uuid = "#bb9af7",
  c_preprocessor = "#7dcfff",
  c_identifier = "#9ece6a",
  c_unclosed_string = "#f7768e",
  c_verbatim_string = "#7aa2f7",
  c_comment_line_doc = "#9d7cd8",
  c_keyword_set2 = "#ff9e64",
  c_comment_doc_keyword = "#7aa2f7",
  c_comment_doc_keyword_error = "#f7768e",
  c_global_class = "#e0af68",
  c_raw_string = "#9ece6a",
  c_triple_quoted_verbatim_string = "#73daca",
  c_hash_quoted_string = "#ff9e64",
  c_preprocessor_comment = "#41a6b5",
  c_preprocessor_comment_line_doc = "#bb9af7",

  -- HTML specific colors
  html_tag = "#f7768e",
  html_unknown_tag = "#f7768e",
  html_attribute = "#9ece6a",
  html_unknown_attribute = "#bb9af7",
  html_other_in_tag = "#7aa2f7",
  html_entity = "#9d7cd8",
  html_tag_end = "#f7768e",
  html_xml_start = "#7aa2f7",
  html_xml_end = "#7aa2f7",
  html_script = "#ff9e64",
  html_asp_at_start = "#f7768e",
  html_asp_start = "#f7768e",
  html_cdata = "#565f89",
  html_php_start = "#bb9af7",
  html_value = "#9ece6a",

  -- CSS specific colors
  css_tag = "#f7768e",
  css_class = "#9ece6a",
  css_pseudo_class = "#9d7cd8",
  css_unknown_pseudo_class = "#f7768e",
  css_property = "#7aa2f7",
  css_unknown_property = "#f7768e",
  css_value = "#bb9af7",
  css_id_selector = "#ff9e64",
  css_important = "#f7768e",
  css_at_rule = "#7aa2f7",
  css_attribute = "#9ece6a",
  css_pseudo_element = "#9d7cd8",
  css_extended_property = "#7aa2f7",
  css_extended_pseudo_class = "#9d7cd8",
  css_extended_pseudo_element = "#9d7cd8",

  -- JSON specific colors
  json_unclosed_string = "#f7768e",
  json_property = "#7aa2f7",
  json_escape_sequence = "#bb9af7",
  json_iri = "#7aa2f7",
  json_iri_compact = "#7aa2f7",
  json_keyword_ld = "#9d7cd8",
  json_error = "#f7768e",

  -- Lua specific colors
  lua_literal_string = "#9ece6a",
  lua_preprocessor = "#ff9e64",
  lua_unclosed_string = "#f7768e",
  lua_basic_functions = "#7aa2f7",
  lua_string_table_maths_functions = "#7dcfff",
  lua_coroutines_io_system_facilities = "#9d7cd8",
  lua_keyword_set5 = "#f7768e",
  lua_keyword_set6 = "#f7768e",
  lua_keyword_set7 = "#f7768e",
  lua_keyword_set8 = "#f7768e",
  lua_label = "#bb9af7",

  -- Markdown specific colors
  md_default = "#c0caf5",
  md_header = "#7aa2f7",
  md_code = "#9ece6a",
  md_link = "#7dcfff",
  md_url = "#bb9af7",
  md_blockquote = "#73daca",
  md_emphasis = "#ff9e64",
  md_strong = "#f7768e",
  md_list_item = "#e0af68",
  md_horizontal_rule = "#414868",
  md_code_block = "#9ece6a",
  md_code_block_bg = "#292e42",
  md_comment = "#565f89",

  -- XML specific colors
  xml_tag = "#f7768e",
  xml_unknown_tag = "#f7768e",
  xml_attribute = "#9ece6a",
  xml_unknown_attribute = "#bb9af7",
  xml_other_in_tag = "#7aa2f7",
  xml_entity = "#9d7cd8",
  xml_tag_end = "#f7768e",
  xml_start = "#7aa2f7",
  xml_end = "#7aa2f7",
  xml_script = "#ff9e64",
  xml_cdata = "#565f89",
  xml_question = "#bb9af7",
  xml_value = "#9ece6a",

  -- YAML specific colors
  yaml_identifier = "#9ece6a",
  yaml_reference = "#7aa2f7",
  yaml_document_delimiter = "#f7768e",
  yaml_text_block_marker = "#bb9af7",
  yaml_syntax_error_marker = "#f7768e",

  -- Java specific colors
  java_identifier = "#9ece6a",
  java_javadoc = "#565f89",
  java_javadoc_keyword = "#bb9af7",

  -- Perl specific colors
  perl_error = "#f7768e",
  perl_pod = "#565f89",
  perl_identifier = "#9ece6a",
  perl_scalar = "#bb9af7",
  perl_array = "#ff9e64",
  perl_hash = "#7dcfff",
  perl_symbol_table = "#9d7cd8",
  perl_substitution = "#f7768e",
  perl_backtick_here_document = "#7aa2f7",
  perl_quoted_string_q = "#9ece6a",
  perl_quoted_string_qq = "#b4f9f8",
  perl_quoted_string_qx = "#e0af68",
  perl_quoted_string_qr = "#bb9af7",
  perl_quoted_string_qw = "#41a6b5",
  perl_pod_verbatim = "#73daca",
  perl_subroutine_prototype = "#ff9e64",
  perl_format_identifier = "#f7768e",
  perl_format_body = "#bb9af7",

  -- Bash specific colors
  bash_error = "#f7768e",
  bash_identifier = "#9ece6a",
  bash_scalar = "#bb9af7",
  bash_parameter_expansion = "#ff9e64",
  bash_backticks = "#7dcfff",
  bash_here_document_delimiter = "#9d7cd8",
  bash_single_quoted_here_document = "#7aa2f7",

  -- Batch specific colors
  batch_label = "#bb9af7",
  batch_hide_command_char = "#7dcfff",
  batch_external_command = "#ff9e64",
  batch_variable = "#9ece6a",

  -- CMake specific colors
  cmake_string_left_quote = "#bb9af7",
  cmake_string_right_quote = "#bb9af7",
  cmake_variable = "#9ece6a",
  cmake_label = "#ff9e64",
  cmake_keyword_set3 = "#7dcfff",
  cmake_block_while = "#9d7cd8",
  cmake_block_foreach = "#f7768e",
  cmake_block_if = "#7aa2f7",
  cmake_block_macro = "#b4f9f8",
  cmake_string_variable = "#e0af68",

  -- SQL specific colors
  sql_comment_doc = "#565f89",
  sql_plus_keyword = "#bb9af7",
  sql_plus_prompt = "#ff9e64",
  sql_identifier = "#9ece6a",
  sql_plus = "#7dcfff",
  sql_plus_command = "#9d7cd8",
  sql_quoted_identifier = "#f7768e",
  sql_q_operator = "#7aa2f7",

  -- Ruby specific colors
  ruby_error = "#f7768e",
  ruby_pod = "#565f89",
  ruby_identifier = "#9ece6a",
  ruby_global = "#bb9af7",
  ruby_symbol = "#ff9e64",
  ruby_module_name = "#7dcfff",
  ruby_instance_variable = "#9d7cd8",
  ruby_class_variable = "#f7768e",
  ruby_backtick_here_document = "#7aa2f7",
  ruby_here_document = "#b4f9f8",
  ruby_percent_string_q = "#e0af68",
  ruby_percent_string_Q = "#bb9af7",

  -- Properties specific colors
  prop_default = "#c0caf5",
  prop_key = "#7dcfff",
  prop_section = "#e0af68",
  prop_assignment = "#73daca",
  prop_value = "#9ece6a",
  prop_comment = "#565f89",
}
