name: Build and Ship Zenith as One-File

on:
  push:
    branches:
      - main

jobs:
  build-and-zip:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Create and Activate Virtual Environment
        run: |
          python -m venv .venv
          .venv\Scripts\Activate.ps1
        shell: pwsh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build One-File EXE
        run: echo Yes | python -m nuitka --onefile --include-data-dir=zenith/media=zenith/media --include-data-files=zenith/shortcuts.json=zenith/shortcuts.json --enable-plugin=pyqt6 --windows-console-mode=disable --windows-icon-from-ico=zenith/media/icon.ico Nyxtext.py

      - name: Zip One-File Version
        run: | 
          Remove-Item -Path Zenith_OneFile.zip -ErrorAction Ignore
          Compress-Archive -Path Nyxtext.dist\* -DestinationPath Zenith_OneFile.zip -Force

      - name: Upload One-File ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zenith-OneFile
          path: Zenith_OneFile.zip
